/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppScribbleRouteImport } from './routes/_app/scribble'
import { Route as AppReferencesRouteImport } from './routes/_app/references'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppNewRouteImport } from './routes/_app/new'
import { Route as AppLiveRouteImport } from './routes/_app/live'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppConnectRouteImport } from './routes/_app/connect'
import { Route as AppBrainRouteImport } from './routes/_app/brain'
import { Route as AppTrackIdRouteImport } from './routes/_app/track.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScribbleRoute = AppScribbleRouteImport.update({
  id: '/scribble',
  path: '/scribble',
  getParentRoute: () => AppRoute,
} as any)
const AppReferencesRoute = AppReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppBrainRoute = AppBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackIdRoute = AppTrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brain': typeof AppBrainRoute
  '/connect': typeof AppConnectRoute
  '/journal': typeof AppJournalRoute
  '/library': typeof AppLibraryRoute
  '/live': typeof AppLiveRoute
  '/new': typeof AppNewRoute
  '/onboarding': typeof AppOnboardingRoute
  '/references': typeof AppReferencesRoute
  '/scribble': typeof AppScribbleRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/track/$id': typeof AppTrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brain': typeof AppBrainRoute
  '/connect': typeof AppConnectRoute
  '/journal': typeof AppJournalRoute
  '/library': typeof AppLibraryRoute
  '/live': typeof AppLiveRoute
  '/new': typeof AppNewRoute
  '/onboarding': typeof AppOnboardingRoute
  '/references': typeof AppReferencesRoute
  '/scribble': typeof AppScribbleRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/track/$id': typeof AppTrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/brain': typeof AppBrainRoute
  '/_app/connect': typeof AppConnectRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/live': typeof AppLiveRoute
  '/_app/new': typeof AppNewRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/references': typeof AppReferencesRoute
  '/_app/scribble': typeof AppScribbleRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/track/$id': typeof AppTrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brain'
    | '/connect'
    | '/journal'
    | '/library'
    | '/live'
    | '/new'
    | '/onboarding'
    | '/references'
    | '/scribble'
    | '/settings'
    | '/stats'
    | '/track/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brain'
    | '/connect'
    | '/journal'
    | '/library'
    | '/live'
    | '/new'
    | '/onboarding'
    | '/references'
    | '/scribble'
    | '/settings'
    | '/stats'
    | '/track/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/brain'
    | '/_app/connect'
    | '/_app/journal'
    | '/_app/library'
    | '/_app/live'
    | '/_app/new'
    | '/_app/onboarding'
    | '/_app/references'
    | '/_app/scribble'
    | '/_app/settings'
    | '/_app/stats'
    | '/_app/track/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scribble': {
      id: '/_app/scribble'
      path: '/scribble'
      fullPath: '/scribble'
      preLoaderRoute: typeof AppScribbleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/references': {
      id: '/_app/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof AppReferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live': {
      id: '/_app/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brain': {
      id: '/_app/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof AppBrainRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/track/$id': {
      id: '/_app/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof AppTrackIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBrainRoute: typeof AppBrainRoute
  AppConnectRoute: typeof AppConnectRoute
  AppJournalRoute: typeof AppJournalRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppLiveRoute: typeof AppLiveRoute
  AppNewRoute: typeof AppNewRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppReferencesRoute: typeof AppReferencesRoute
  AppScribbleRoute: typeof AppScribbleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppTrackIdRoute: typeof AppTrackIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrainRoute: AppBrainRoute,
  AppConnectRoute: AppConnectRoute,
  AppJournalRoute: AppJournalRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppLiveRoute: AppLiveRoute,
  AppNewRoute: AppNewRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppReferencesRoute: AppReferencesRoute,
  AppScribbleRoute: AppScribbleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatsRoute: AppStatsRoute,
  AppTrackIdRoute: AppTrackIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
